# Generated by Django 5.2.6 on 2025-09-24 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('user', 'date', 'time')},
        ),
    ]
